/*
 * This source file was generated by the Gradle 'init' task
 */
package org.dru;

import com.fazecast.jSerialComm.SerialPort;
import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;
import javafx.scene.control.Button;
import javafx.scene.control.Label;

public class App extends Application {

    public void start(Stage stage) {
        Label label = new Label("Benvenuto in JavaFX!");
        Button button = new Button("Cliccami");

        button.setOnAction(e -> label.setText("Bottone premuto!"));

        VBox layout = new VBox(20);
        layout.getChildren().addAll(label, button);

        Scene scene = new Scene(layout, 300, 200);

        stage.setTitle("Esempio JavaFX");
        stage.setScene(scene);
        stage.show();
    }

    public static void main(String[] args) {
        launch(args);
        SerialPort port = SerialPort.getCommPorts()[0]; // seleziona la porta
        port.setBaudRate(9600);

        if(port.openPort()) {
            System.out.println("Porta aperta!");

            new Thread(() -> {
                while (true) {
                    if(port.bytesAvailable() > 0) {
                        byte[] buffer = new byte[port.bytesAvailable()];
                        port.readBytes(buffer, buffer.length);
                        System.out.print(new String(buffer));
                    }
                }
            }).start();
        }
    }
}
